// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/auth.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthProtoService_CheckAccess_FullMethodName = "/auth.AuthProtoService/CheckAccess"
)

// AuthProtoServiceClient is the client API for AuthProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthProtoServiceClient interface {
	// Проверка прав
	CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error)
}

type authProtoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthProtoServiceClient(cc grpc.ClientConnInterface) AuthProtoServiceClient {
	return &authProtoServiceClient{cc}
}

func (c *authProtoServiceClient) CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccessResponse)
	err := c.cc.Invoke(ctx, AuthProtoService_CheckAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthProtoServiceServer is the server API for AuthProtoService service.
// All implementations must embed UnimplementedAuthProtoServiceServer
// for forward compatibility.
type AuthProtoServiceServer interface {
	// Проверка прав
	CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error)
	mustEmbedUnimplementedAuthProtoServiceServer()
}

// UnimplementedAuthProtoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthProtoServiceServer struct{}

func (UnimplementedAuthProtoServiceServer) CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAccess not implemented")
}
func (UnimplementedAuthProtoServiceServer) mustEmbedUnimplementedAuthProtoServiceServer() {}
func (UnimplementedAuthProtoServiceServer) testEmbeddedByValue()                          {}

// UnsafeAuthProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthProtoServiceServer will
// result in compilation errors.
type UnsafeAuthProtoServiceServer interface {
	mustEmbedUnimplementedAuthProtoServiceServer()
}

func RegisterAuthProtoServiceServer(s grpc.ServiceRegistrar, srv AuthProtoServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthProtoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthProtoService_ServiceDesc, srv)
}

func _AuthProtoService_CheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthProtoServiceServer).CheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthProtoService_CheckAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthProtoServiceServer).CheckAccess(ctx, req.(*CheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthProtoService_ServiceDesc is the grpc.ServiceDesc for AuthProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthProtoService",
	HandlerType: (*AuthProtoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAccess",
			Handler:    _AuthProtoService_CheckAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}
