env: local

database:
  port: 5432
  driver: "postgres"
  user: user
  password: password
  database: db
  host: db
  ssl_mode: disable
  migrations_path: ./migrations

server:
  port: 8082

auth:
  client:
    grpc_address: "auth-service:50051"
    timeout: 5s

storage:
  type: "minio"
  minio:
    endpoint: "minio.localtest.me:9000"
    access_key_id: "minioadmin"
    secret_access_key: "minioadmin"
    use_ssl: false
    bucket_name: "dormitory-life"
    public_url: "http://minio.localtest.me:9000"

broker:
  port: 5672
  host: "broker"
  user: admin
  password: admin

broker_queues:
  support_queue: support_queue

emailer:
  host: smtp.mail.ru
  port: 587
  user: 
  password: 
  email: 

cache:
  addr: "cache:6379"
  password: admin
  max_retries: 3
  timeout: 5s
  dial_timeout: 5s
